version: "3.8"

services:
  go:
    image: go-app
    build: # Use the Dockerfile from the current directory to build container.
      context: .
    container_name: c-go-app
    ports:
      - "8080:8080"
    depends_on:
      - "db"

  db:
    image: mysql # use latest version of mysql
    container_name: c-mysql # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: crud_go # create this database on startup
      MYSQL_TCP_PORT: 3307
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3307:3307"

volumes: # add volume to persist data.
  my-db:
