#!/bin/sh
name="devis"
tgl=$(date)
nameFile="$name $tgl"
mkdir -p "$nameFile"/about_me/personal
chmod 777 "$nameFile"
cd "$nameFile"
chmod 777 about_me
cd about_me
chmod 777 personal
mkdir profesional
chmod 777 profesional
cd personal
touch facebook.txt
chmod 777 facebook.txt
fb="https://www.facebook.com/"
echo "$fb$2">facebook.txt
cd ..
cd profesional
touch linkedin.txt
chmod 777 linkedin.txt
linkedin="https://www.linkedin.com/in/"
echo "$linkedin$3">linkedin.txt
cd ..
cd ..
mkdir my_friends my_system_info
chmod 777 my_friends
chmod 777 my_system_info
cd my_friends
touch list_of_my_friends.txt
chmod 777 list_of_my_friends.txt
curl=$(curl https://gist.githubusercontent.com/tegarimansyah/e91f335753ab2c7fb12815779677e914/raw/94864388379fecee450fde26e3e73bfb2bcda194/list%2520of%2520my%2520friends.txt)
echo "$curl" > list_of_my_friends.txt
cd ..
cd my_system_info
touch about_this_laptop.txt
chmod 777 about_this_laptop.txt
echo "Username: $1">about_this_laptop.txt
uname=$(uname -a)
echo "With Host: $uname">>about_this_laptop.txt
touch internet_connection.txt
chmod 777 internet_connection.txt
internet=$(ping -c 3 google.com)
echo "$internet">internet_connection.txt
